Repository MissouriMRDT/BaseStation_Software, pull requests merged in 2023-10, with the labels that each got.

#252 Removed digital sliders, added physical slider support
  assets/ControllerInput.json
  src/Core/components/ControlScheme.tsx
  src/RAM/Arm/Arm.tsx
  src/RAM/Arm/components/ControlMultipliers.tsx
  src/RED/ControlCenter.tsx
  src/RID/RID.tsx
Labels: enhancement, 2-Star

#257 GitHub Actions Optimizations
  .erb/configs/webpack.config.eslint.js
  .github/workflows/deploy_basestation.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  src/RAM/Arm/Arm.tsx
  src/RAM/Arm/components/Angular.tsx
  src/RAM/Arm/components/IK.tsx
  src/RAM/Autonomy/components/StateDiagram.tsx
  src/RAM/Science/Science.tsx
  src/RAM/Science/components/EncoderPositions.tsx
  src/RAM/Science/components/Fluorometer.tsx
  src/RED/components/Map.tsx
  src/RED/components/Power&BMS.tsx
  src/RED/components/Waypoints.tsx
  src/RID/RID.tsx
  src/RON/components/PingTool.tsx
  src/main.dev.ts
Labels: enhancement

#273 Implemented loader-utils-2.0
  package.json
Labels: dependencies

#292 Updated to loader-utils to 3.2.1 for more security alerts
  package.json
  yarn.lock
Labels: dependencies
